import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsOptional } from 'class-validator';

interface content {
  encrypted: string;
  nonce: string;
}
export class CreateMessageDto {
  @IsNotEmpty()
  @ApiProperty({
    description: 'Receiver ID',
    example: 'user-uuid',
  })
  receiver_id: string;

  @IsNotEmpty()
  @ApiProperty({
    description: 'Content of the message',
    example: 'Hello, how are you?',
  })
  content: content;

  // @IsNotEmpty()
  @IsOptional()
  @ApiProperty({
    description: 'Content of the message',
    example: 'Hello, how are you?',
  })
  content_copy: content;

  @IsNotEmpty()
  @ApiProperty({
    description: 'Unique Message Id Generated by Fronted',
  })
  uniqueId: string;
}
